# Generated by Django 4.2.4 on 2023-11-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('fechayHoraDeReserva', models.DateTimeField()),
                ('cantidadDePersonas', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('estado', models.CharField(max_length=30)),
                ('observacione', models.CharField(max_length=100)),
            ],
        ),
    ]
