# Generated by Django 4.2.4 on 2023-11-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='observacione',
        ),
        migrations.AddField(
            model_name='reservas',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
