# Generated by Django 4.2.7 on 2023-11-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reservas_observacione_reservas_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservas',
            name='nombre',
            field=models.CharField(max_length=80),
        ),
    ]
